apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: default
type: Opaque
data:
  # Cloudflare Access Token from .env file (base64 encoded)
  api-token: OWxlUEM2YTZsOGFhd0J0ei1kZjRLbk1Ua0NZeGRHSnBpamR2Ymd0UQ==