---
# This file contains templates that will be used by the k8sgo application
# to dynamically create IngressRoute resources for each user sandbox

# Template for VNC access (port 6901)
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: user-vnc-template
  namespace: default
  annotations:
    # This is a template - not to be applied directly
    external-dns.alpha.kubernetes.io/target: traefik.tryiris.dev
    external-dns.alpha.kubernetes.io/ttl: "60"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{.UserID}}-vnc.tryiris.dev`)
      kind: Rule
      services:
        - name: {{.UserID}}-sandbox
          port: 6901
  tls:
    certResolver: cloudflare

---
# Template for HTTP/API access (port 3000)
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: user-api-template
  namespace: default
  annotations:
    # This is a template - not to be applied directly
    external-dns.alpha.kubernetes.io/target: traefik.tryiris.dev
    external-dns.alpha.kubernetes.io/ttl: "60"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{.UserID}}-api.tryiris.dev`)
      kind: Rule
      services:
        - name: {{.UserID}}-sandbox
          port: 3000
  tls:
    certResolver: cloudflare