{{- if .Values.ingress.enabled -}}
{{- $fullName := include "k8s-orchestrator.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "k8s-orchestrator.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.cloudProvider.aws.enabled }}
    {{- with .Values.cloudProvider.aws.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- else if .Values.cloudProvider.gcp.enabled }}
    {{- with .Values.cloudProvider.gcp.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- else }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.cloudProvider.aws.enabled }}
  ingressClassName: {{ .Values.cloudProvider.aws.ingressClass }}
  {{- else if .Values.cloudProvider.gcp.enabled }}
  ingressClassName: {{ .Values.cloudProvider.gcp.ingressClass }}
  {{- else if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}