additionalArguments:
  # Providers configuration
  - "--providers.kubernetesingress.ingressclass=traefik"
  - "--providers.kubernetescrd.allowCrossNamespace=true"

  # Entrypoint addresses
  - "--entrypoints.web.address=:8000/tcp"
  - "--entrypoints.websecure.address=:8443/tcp"

  # HTTP to HTTPS redirection
  - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
  - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
  - "--entrypoints.websecure.http.tls=true"

  # Let's Encrypt configuration
  - "--certificatesresolvers.letsencrypt.acme.email=admin@tryiris.dev"
  - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
  - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"

  # Additional ports for VNC service
  - "--entrypoints.vnc.address=:5901/tcp"
  - "--entrypoints.vncweb.address=:6901/tcp"

# Port configuration
ports:
  # Use higher port numbers to avoid privileged port issues
  web:
    port: 8000
    expose:
      default: true
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 8443
    expose:
      default: true
    exposedPort: 443
    protocol: TCP
  vnc:
    port: 5901
    expose:
      default: true
    exposedPort: 5901
    protocol: TCP
  vncweb:
    port: 6901
    expose:
      default: true
    exposedPort: 6901
    protocol: TCP

# Make Traefik the default ingress class
ingressClass:
  enabled: true
  isDefaultClass: true

# Resource requirements
resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

# Persistent storage for Let's Encrypt certificates
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 128Mi
  path: /data

# Init container to fix permissions
initContainers:
  - name: setup-acme
    image: busybox
    command: ["sh", "-c", "touch /data/acme.json && chmod 600 /data/acme.json"]
    volumeMounts:
      - name: data
        mountPath: /data

# Security context for improved permissions
securityContext:
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true

# Dashboard and API
dashboard:
  enabled: true