# Local development values for k8s-orchestrator

# Docker Desktop / Minikube specific settings
replicaCount: 1

# Use the local image
image:
  repository: k8s-orchestrator
  pullPolicy: Never
  tag: "latest"

# Cloud provider configuration - all disabled for local dev
cloudProvider:
  aws:
    enabled: false
  gcp:
    enabled: false

# Environment configuration
env:
  DOMAIN: "pods.tryiris.dev"
  PORT: "8080"

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: api.pods.tryiris.dev
      paths:
        - path: /
          pathType: Prefix
  tls: []  # No TLS for local development

# Reduced resources for local development
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Disable autoscaling for local development
autoscaling:
  enabled: false

# User environments with minimal resources
userEnvironments:
  defaultImage: "accetto/ubuntu-vnc-xfce-firefox-g3"
  defaultPorts: [5901, 6901]
  defaultVolumeSize: "1Gi"
  storageClass: "standard"  # Use default storage class

# Disable network policies for local development
networkPolicies:
  enabled: false