# AWS EKS specific values for k8s-orchestrator

# Cloud provider configuration
cloudProvider:
  aws:
    enabled: true
    ingressClass: "alb"
    annotations:
      alb.ingress.kubernetes.io/scheme: "internet-facing"
      alb.ingress.kubernetes.io/target-type: "ip"
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      external-dns.alpha.kubernetes.io/hostname: "api.pods.tryiris.dev"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    storageClass: "gp2"
  gcp:
    enabled: false

# Environment configuration
env:
  DOMAIN: "pods.tryiris.dev"
  PORT: "8080"

# Ingress configuration
ingress:
  enabled: true
  useTraefik: true
  className: "alb"  # Will be overridden by cloudProvider settings when useTraefik is false
  # Traefik specific configuration
  entryPoints: ["web", "websecure"]
  tlsSecretName: "k8s-orchestrator-tls"
  certResolver: "letsencrypt"
  # Middleware configuration for Traefik
  middleware:
    enabled: true
    headers:
      enabled: true
    rateLimit:
      enabled: true
      average: 100
      burst: 50
    compress:
      enabled: true
  hosts:
    - host: api.pods.tryiris.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: k8s-orchestrator-tls
      hosts:
        - api.pods.tryiris.dev

# Image configuration
image:
  repository: shanurcsenitap/irisk8s
  pullPolicy: Always
  tag: "latest"

# Resources
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

# Autoscaling
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

# User environments
userEnvironments:
  defaultImage: "accetto/ubuntu-vnc-xfce-firefox-g3"
  defaultPorts: [5901, 6901]
  defaultVolumeSize: "5Gi"
  storageClass: "gp2"  # Use AWS EBS gp2 storage class

# Network policies
networkPolicies:
  enabled: true