apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8sgo-role
rules:
- apiGroups: ["traefik.io"]
  resources: ["ingressroutes"]
  verbs: ["create", "get", "list", "watch", "update", "delete"]