apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ingressroute-writer
  namespace: user-sandboxes
rules:
- apiGroups:
  - traefik.io
  resources:
  - ingressroutes
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - delete
