apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - service-account.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml