// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/sandbox/{userId}": {
            "post": {
                "description": "Creates a new containerized sandbox for a specific user with Traefik IngressRoutes",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sandbox"
                ],
                "summary": "Create a user sandbox with Traefik routing",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.SandboxResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a containerized sandbox for a specific user including Traefik IngressRoutes",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sandbox"
                ],
                "summary": "Delete a user sandbox with Traefik routing",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ErrorResponse": {
            "description": "Standard API error response",
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error message",
                    "type": "string",
                    "example": "User ID is required"
                }
            }
        },
        "api.Response": {
            "description": "Standard API success response",
            "type": "object",
            "properties": {
                "message": {
                    "description": "Response message",
                    "type": "string",
                    "example": "Sandbox created successfully"
                },
                "userId": {
                    "description": "User ID",
                    "type": "string",
                    "example": "user123"
                }
            }
        },
        "api.SandboxResponse": {
            "description": "Sandbox creation response with URLs",
            "type": "object",
            "properties": {
                "apiUrl": {
                    "description": "API URL for the sandbox",
                    "type": "string",
                    "example": "https://user123-api.tryiris.dev"
                },
                "message": {
                    "description": "Response message",
                    "type": "string",
                    "example": "Sandbox created successfully"
                },
                "userId": {
                    "description": "User ID",
                    "type": "string",
                    "example": "user123"
                },
                "vncUrl": {
                    "description": "VNC URL for the sandbox",
                    "type": "string",
                    "example": "https://user123-vnc.tryiris.dev"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
