definitions:
  api.CleanupResponse:
    description: Cleanup operation response
    properties:
      duration:
        description: Duration used for cleanup
        example: configurable timeout
        type: string
      message:
        description: Response message
        example: Cleanup triggered successfully
        type: string
    type: object
  api.ErrorResponse:
    description: Standard API error response
    properties:
      error:
        description: Error message
        example: User ID is required
        type: string
    type: object
  api.Response:
    description: Standard API success response
    properties:
      message:
        description: Response message
        example: Sandbox created successfully
        type: string
      userId:
        description: User ID
        example: user123
        type: string
    type: object
  api.SandboxListResponse:
    description: List of all sandboxes
    properties:
      count:
        description: Count of sandboxes
        example: 3
        type: integer
      sandboxes:
        description: List of sandboxes
        items:
          $ref: '#/definitions/k8s.SandboxInfo'
        type: array
    type: object
  api.SandboxRequest:
    description: Request to create a new sandbox.
    type: object
  api.SandboxResponse:
    description: Sandbox creation response with URLs
    properties:
      apiUrl:
        description: API URL for the sandbox
        example: https://user123-api.tryiris.dev
        type: string
      message:
        description: Response message
        example: Sandbox created successfully
        type: string
      userId:
        description: User ID
        example: user123
        type: string
      vncUrl:
        description: VNC URL for the sandbox
        example: https://user123-vnc.tryiris.dev
        type: string
    type: object
  api.SandboxStatusResponse:
    description: Response for sandbox status check
    properties:
      createdAt:
        description: Created timestamp
        example: "2023-04-20T12:00:00Z"
        type: string
      exists:
        description: Whether the sandbox exists
        example: true
        type: boolean
      status:
        description: Sandbox status
        example: Running
        type: string
      userId:
        description: User ID
        example: user123
        type: string
    type: object
  k8s.ContainerStatus:
    properties:
      image:
        example: us-central1-docker.pkg.dev/driven-seer-460401-p9/iris-repo/iris_agent:latest
        type: string
      message:
        example: ""
        type: string
      name:
        example: sandbox
        type: string
      ready:
        example: true
        type: boolean
      reason:
        example: ""
        type: string
      restartCount:
        example: 0
        type: integer
      state:
        example: running
        type: string
    type: object
  k8s.SandboxInfo:
    properties:
      containerStatuses:
        items:
          $ref: '#/definitions/k8s.ContainerStatus'
        type: array
      createdAt:
        example: "2023-04-20T12:00:00Z"
        type: string
      initContainerStatuses:
        items:
          $ref: '#/definitions/k8s.ContainerStatus'
        type: array
      message:
        example: ""
        type: string
      podConditions:
        example:
        - '["PodScheduled"'
        - '"Initialized"'
        - '"ContainersReady"'
        - '"Ready"]'
        items:
          type: string
        type: array
      podName:
        example: user123-deployment-5d8b9c7b8f-2p8x7
        type: string
      podPhase:
        example: Running
        type: string
      reason:
        example: ""
        type: string
      status:
        example: Running
        type: string
      userId:
        example: user123
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/admin/cleanup:
    post:
      consumes:
      - application/json
      description: Deletes all sandboxes that have been running for more than the
        specified minutes
      parameters:
      - description: Age in minutes
        in: query
        name: minutes
        required: true
        type: integer
      - description: Authentication token
        in: query
        name: auth
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.CleanupResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Trigger cleanup of old sandboxes with Traefik routing
      tags:
      - admin
  /v1/sandbox/{userId}:
    delete:
      consumes:
      - application/json
      description: Deletes a containerized sandbox for a specific user including Traefik
        IngressRoutes
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Delete a user sandbox with Traefik routing
      tags:
      - sandbox
    post:
      consumes:
      - application/json
      description: Creates a new containerized sandbox for a specific user with Traefik
        IngressRoutes
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      - description: Request body (empty, kept for API compatibility)
        in: body
        name: request
        schema:
          $ref: '#/definitions/api.SandboxRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api.SandboxResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Create a user sandbox with Traefik routing
      tags:
      - sandbox
  /v1/sandbox/{userId}/status:
    get:
      consumes:
      - application/json
      description: Retrieves the status of a sandbox for a specific user with Traefik
        IngressRoutes
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.SandboxStatusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get the status of a user sandbox with Traefik routing
      tags:
      - sandbox
  /v1/sandboxes:
    get:
      consumes:
      - application/json
      description: Retrieves a list of all sandboxes with their status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.SandboxListResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: List all sandboxes with Traefik routing
      tags:
      - sandbox
swagger: "2.0"
