definitions:
  api.ErrorResponse:
    description: Standard API error response
    properties:
      error:
        description: Error message
        example: User ID is required
        type: string
    type: object
  api.Response:
    description: Standard API success response
    properties:
      message:
        description: Response message
        example: Sandbox created successfully
        type: string
      userId:
        description: User ID
        example: user123
        type: string
    type: object
  api.SandboxResponse:
    description: Sandbox creation response with URLs
    properties:
      apiUrl:
        description: API URL for the sandbox
        example: https://user123-api.tryiris.dev
        type: string
      message:
        description: Response message
        example: Sandbox created successfully
        type: string
      userId:
        description: User ID
        example: user123
        type: string
      vncUrl:
        description: VNC URL for the sandbox
        example: https://user123-vnc.tryiris.dev
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/sandbox/{userId}:
    delete:
      consumes:
      - application/json
      description: Deletes a containerized sandbox for a specific user including Traefik
        IngressRoutes
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Delete a user sandbox with Traefik routing
      tags:
      - sandbox
    post:
      consumes:
      - application/json
      description: Creates a new containerized sandbox for a specific user with Traefik
        IngressRoutes
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api.SandboxResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Create a user sandbox with Traefik routing
      tags:
      - sandbox
swagger: "2.0"
